service: doctor-service

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  apiGateway:
    restApiId: 3tkik28qcj
    restApiRootResourceId: 4zbsq6bex0

functions:
  getData:
    handler: handler.getData
    events:
      - http:
          path: test
          method: get
          cors: true

plugins:
  - serverless-offline
